name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "src/**"
      - "project/**"
      - ".scalafmt.conf"
      - ".github/**"
      - "build.sbt"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  scalafmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/setup-action@v1.3.9
        with:
          apps: scalafmt
      - run: scalafmt --test
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            jvm: 'adoptium:1.8.0-372'
          - os: windows-latest
            jvm: 'adoptium:1.11.0.19'
          - os: macOS-latest
            jvm: 'adoptium:1.17.0.7'
          - os: ubuntu-latest
            jvm: 'adoptium:1.20.0.1'
    name: Unit Tests on ${{ matrix.os }} -- ${{ matrix.jvm }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: coursier/setup-action@v1.3.9
      with:
        jvm: ${{ matrix.jvm }}
        apps: sbt
    - name: Unit tests
      run: sbt test
      shell: bash
